# Form implementation generated from reading ui file '.\app\views\design\ventana_crear_archivo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaCrearArchivo(object):
    def setupUi(self, VentanaCrearArchivo):
        VentanaCrearArchivo.setObjectName("VentanaCrearArchivo")
        VentanaCrearArchivo.resize(400, 300)
        self.btn_seleccionar_donde_guardar = QtWidgets.QPushButton(parent=VentanaCrearArchivo)
        self.btn_seleccionar_donde_guardar.setGeometry(QtCore.QRect(110, 30, 161, 24))
        self.btn_seleccionar_donde_guardar.setObjectName("btn_seleccionar_donde_guardar")
        self.btn_crear_archivo = QtWidgets.QPushButton(parent=VentanaCrearArchivo)
        self.btn_crear_archivo.setGeometry(QtCore.QRect(280, 250, 75, 24))
        self.btn_crear_archivo.setObjectName("btn_crear_archivo")
        self.btn_cancelar = QtWidgets.QPushButton(parent=VentanaCrearArchivo)
        self.btn_cancelar.setGeometry(QtCore.QRect(170, 250, 75, 24))
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.input_nombre_archivo = QtWidgets.QLineEdit(parent=VentanaCrearArchivo)
        self.input_nombre_archivo.setGeometry(QtCore.QRect(190, 110, 113, 21))
        self.input_nombre_archivo.setObjectName("input_nombre_archivo")
        self.input_contasena = QtWidgets.QLineEdit(parent=VentanaCrearArchivo)
        self.input_contasena.setGeometry(QtCore.QRect(190, 140, 113, 21))
        self.input_contasena.setObjectName("input_contasena")
        self.label = QtWidgets.QLabel(parent=VentanaCrearArchivo)
        self.label.setGeometry(QtCore.QRect(70, 110, 121, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=VentanaCrearArchivo)
        self.label_2.setGeometry(QtCore.QRect(70, 140, 71, 20))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(VentanaCrearArchivo)
        QtCore.QMetaObject.connectSlotsByName(VentanaCrearArchivo)

    def retranslateUi(self, VentanaCrearArchivo):
        _translate = QtCore.QCoreApplication.translate
        VentanaCrearArchivo.setWindowTitle(_translate("VentanaCrearArchivo", "Dialog"))
        self.btn_seleccionar_donde_guardar.setText(_translate("VentanaCrearArchivo", "Seleccionar donde guardar"))
        self.btn_crear_archivo.setText(_translate("VentanaCrearArchivo", "Crear"))
        self.btn_cancelar.setText(_translate("VentanaCrearArchivo", "Cancelar"))
        self.label.setText(_translate("VentanaCrearArchivo", "Nombre del archivo:"))
        self.label_2.setText(_translate("VentanaCrearArchivo", "Contraseña:"))
