# Form implementation generated from reading ui file '.\app\views\qt\design\ventana_crear_archivo.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaCrearArchivo(object):
    def setupUi(self, VentanaCrearArchivo):
        VentanaCrearArchivo.setObjectName("VentanaCrearArchivo")
        VentanaCrearArchivo.resize(500, 350)
        self.btn_seleccionar_donde_guardar = QtWidgets.QPushButton(parent=VentanaCrearArchivo)
        self.btn_seleccionar_donde_guardar.setGeometry(QtCore.QRect(120, 20, 241, 24))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.btn_seleccionar_donde_guardar.setFont(font)
        self.btn_seleccionar_donde_guardar.setObjectName("btn_seleccionar_donde_guardar")
        self.input_nombre_archivo = QtWidgets.QLineEdit(parent=VentanaCrearArchivo)
        self.input_nombre_archivo.setGeometry(QtCore.QRect(260, 120, 113, 21))
        self.input_nombre_archivo.setObjectName("input_nombre_archivo")
        self.label = QtWidgets.QLabel(parent=VentanaCrearArchivo)
        self.label.setGeometry(QtCore.QRect(140, 120, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=VentanaCrearArchivo)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(170, 180, 171, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_crear_archivo = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.btn_crear_archivo.setFont(font)
        self.btn_crear_archivo.setObjectName("btn_crear_archivo")
        self.horizontalLayout.addWidget(self.btn_crear_archivo)
        self.btn_cancelar = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.btn_cancelar.setFont(font)
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.horizontalLayout.addWidget(self.btn_cancelar)
        self.label_ruta_carpeta = QtWidgets.QLabel(parent=VentanaCrearArchivo)
        self.label_ruta_carpeta.setGeometry(QtCore.QRect(40, 50, 421, 51))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.label_ruta_carpeta.setFont(font)
        self.label_ruta_carpeta.setText("")
        self.label_ruta_carpeta.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_ruta_carpeta.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_ruta_carpeta.setWordWrap(True)
        self.label_ruta_carpeta.setObjectName("label_ruta_carpeta")

        self.retranslateUi(VentanaCrearArchivo)
        QtCore.QMetaObject.connectSlotsByName(VentanaCrearArchivo)

    def retranslateUi(self, VentanaCrearArchivo):
        _translate = QtCore.QCoreApplication.translate
        VentanaCrearArchivo.setWindowTitle(_translate("VentanaCrearArchivo", "UIDEPASS"))
        self.btn_seleccionar_donde_guardar.setText(_translate("VentanaCrearArchivo", "Seleccionar donde guardar"))
        self.label.setText(_translate("VentanaCrearArchivo", "Nombre del archivo:"))
        self.btn_crear_archivo.setText(_translate("VentanaCrearArchivo", "Crear"))
        self.btn_cancelar.setText(_translate("VentanaCrearArchivo", "Cancelar"))
