# Form implementation generated from reading ui file '.\app\views\qt\design\ventana_principal.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaPrincipal(object):
    def setupUi(self, VentanaPrincipal):
        VentanaPrincipal.setObjectName("VentanaPrincipal")
        VentanaPrincipal.resize(500, 350)
        self.label = QtWidgets.QLabel(parent=VentanaPrincipal)
        self.label.setGeometry(QtCore.QRect(160, 20, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Lucida Calligraphy")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=VentanaPrincipal)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 60, 391, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_crear_archivo = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        font.setItalic(False)
        self.btn_crear_archivo.setFont(font)
        self.btn_crear_archivo.setObjectName("btn_crear_archivo")
        self.horizontalLayout.addWidget(self.btn_crear_archivo)
        self.btn_seleccionar_archivo = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.btn_seleccionar_archivo.setFont(font)
        self.btn_seleccionar_archivo.setObjectName("btn_seleccionar_archivo")
        self.horizontalLayout.addWidget(self.btn_seleccionar_archivo)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=VentanaPrincipal)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 210, 231, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_ver_contrasenas = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.btn_ver_contrasenas.setFont(font)
        self.btn_ver_contrasenas.setObjectName("btn_ver_contrasenas")
        self.verticalLayout.addWidget(self.btn_ver_contrasenas)
        self.label_ruta_archivo = QtWidgets.QLabel(parent=VentanaPrincipal)
        self.label_ruta_archivo.setGeometry(QtCore.QRect(40, 160, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(10)
        self.label_ruta_archivo.setFont(font)
        self.label_ruta_archivo.setLineWidth(1)
        self.label_ruta_archivo.setText("")
        self.label_ruta_archivo.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_ruta_archivo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_ruta_archivo.setWordWrap(True)
        self.label_ruta_archivo.setObjectName("label_ruta_archivo")

        self.retranslateUi(VentanaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(VentanaPrincipal)

    def retranslateUi(self, VentanaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        VentanaPrincipal.setWindowTitle(_translate("VentanaPrincipal", "UIDEPASS"))
        self.label.setText(_translate("VentanaPrincipal", "UIDEPASS"))
        self.btn_crear_archivo.setText(_translate("VentanaPrincipal", "Crear archivo"))
        self.btn_seleccionar_archivo.setText(_translate("VentanaPrincipal", "Seleccionar archivo"))
        self.btn_ver_contrasenas.setText(_translate("VentanaPrincipal", "Ver contraseñas"))
