# Form implementation generated from reading ui file '.\app\views\qt\design\ventana_lista_contrasenas.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_VentanaListaContrasenas(object):
    def setupUi(self, VentanaListaContrasenas):
        VentanaListaContrasenas.setObjectName("VentanaListaContrasenas")
        VentanaListaContrasenas.resize(613, 532)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=VentanaListaContrasenas)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 40, 381, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_crear_nueva = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btn_crear_nueva.setObjectName("btn_crear_nueva")
        self.horizontalLayout.addWidget(self.btn_crear_nueva)
        self.btn_cerrar_sesion = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btn_cerrar_sesion.setObjectName("btn_cerrar_sesion")
        self.horizontalLayout.addWidget(self.btn_cerrar_sesion)
        self.table_lista_contrasenas = QtWidgets.QTableView(parent=VentanaListaContrasenas)
        self.table_lista_contrasenas.setGeometry(QtCore.QRect(140, 160, 351, 291))
        self.table_lista_contrasenas.setObjectName("table_lista_contrasenas")

        self.retranslateUi(VentanaListaContrasenas)
        QtCore.QMetaObject.connectSlotsByName(VentanaListaContrasenas)

    def retranslateUi(self, VentanaListaContrasenas):
        _translate = QtCore.QCoreApplication.translate
        VentanaListaContrasenas.setWindowTitle(_translate("VentanaListaContrasenas", "Dialog"))
        self.btn_crear_nueva.setText(_translate("VentanaListaContrasenas", "Crear nueva"))
        self.btn_cerrar_sesion.setText(_translate("VentanaListaContrasenas", "Cerrar sesión"))
